export default [
    { path: '/',name: 'login2', component: require('./components/auth/Login.vue').default },
    { path: '/pin-code',name: 'pin-code', component: require('./components/auth/PinCode.vue').default },
    { path: '/register',name: 'register', component: require('./components/auth/Register.vue').default },
    { path: '/login',name: 'login', component: require('./components/auth/Login.vue').default },
    { path: '/recovery',name: 'recovery', component: require('./components/auth/Recovery.vue').default },
    { path: '/new-password/:token',name: 'new-password', component: require('./components/auth/NewPassword.vue').default },
    { path: '/first-payment',name: 'first-payment', component: require('./components/payment/FirstPayment.vue').default },
    { path: '/patients',name: 'patients', component: require('./components/patient/List.vue').default },
    { path: '/patients/newPatient',name: 'newPatient', component: require('./components/patient/NewPatient.vue').default },
    { path: '/patients/card/:id',name: 'patient-card', component: require('./components/patient/Card.vue').default },
    { path: '/patients/form_043/:id?',name: 'patient-form_043', component: require('./components/patient/Form043.vue').default },
    { path: '/patients/form_043/:id/print',name: 'patient-form_043-print', component: require('./components/patient/Form043Print.vue').default },
    { path: '/patients/agreements/:id',name: 'patient-agreements', component: require('./components/patient/Agreements.vue').default },
    { path: '/patients/files/:id',name: 'patient-files', component: require('./components/patient/Files.vue').default },
    { path: '/profile',name: 'profile', component: require('./components/cabinet/Profile.vue').default },
    { path: '/clinic',name: 'clinic', component: require('./components/cabinet/Clinic.vue').default },
    { path: '/worker',name: 'worker', component: require('./components/cabinet/Worker.vue').default },
    { path: '/payment',name: 'payment', component: require('./components/cabinet/Payment.vue').default },
    { path: '/sub/payment',name: 'sub-payment', component: require('./components/payment/SubPayment.vue').default },
    { path: '/field-template',name: 'field-template', component: require('./components/cabinet/FieldTemplate.vue').default },
    { path: '/ticket/form',name: 'ticket-form', component: require('./components/cabinet/Ticket.vue').default },
    { path: '/faq',name: 'faq', component: require('./components/cabinet/Faq.vue').default },
    { path: '/video/list',name: 'video', component: require('./components/cabinet/Video.vue').default },
    { path: '/thank-you',name: 'thank-you', component: require('./components/cabinet/ThankYou.vue').default },
    { path: '/patients/form_oftol/:id?',name: 'patient-form_oftol', component: require('./components/patient/FormOftalmolog.vue').default },
    { path: '/patients/form_oftol/:id/print',name: 'patient-form_oftol-print', component: require('./components/patient/FormOftalmologPrint.vue').default },
    { path: '/patients/consult/print/:id/:pageNum',name: 'patient-consult-print', component: require('./components/patient/Form025ModalPrint.vue').default },
    { path: '*',      component: require('./components/NotFound.vue').default }
];
